# Generated by Django 5.2.6 on 2026-06-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='valor_notas',
            new_name='puntos_experiencia',
        ),
        migrations.AlterField(
            model_name='activity',
            name='tipo',
            field=models.CharField(choices=[('reto', 'Reto'), ('mision', 'Misión'), ('proyecto', 'Proyecto'), ('evaluacion', 'Evaluación')], max_length=20),
        ),
    ]
