# Generated by Django 5.2.6 on 2026-10-07 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de contacto')),
                ('tipo', models.CharField(choices=[('bug', 'Error o fallo del sistema'), ('sugerencia', 'Sugerencia o mejora'), ('educoins', 'Problema con EduCoins / Subastas'), ('academico', 'Dificultad con actividades / notas'), ('otro', 'Otro asunto')], default='bug', max_length=20, verbose_name='Tipo de reporte')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('pagina_origen', models.CharField(blank=True, max_length=300, null=True, verbose_name='Página de origen')),
                ('navegador_info', models.CharField(blank=True, max_length=300, null=True, verbose_name='Información de navegador/dispositivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte de Usuario',
                'verbose_name_plural': 'Reportes de Usuarios',
                'ordering': ['-creado'],
            },
        ),
    ]
