# Generated by Django 5.2.6 on 2026-06-11 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='institutions.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('actividad', 'Nueva Actividad'), ('calificacion', 'Calificación Recibida'), ('monedas', 'Monedas Recibidas'), ('subasta_nueva', 'Nueva Subasta'), ('subasta_ganada', 'Subasta Ganada'), ('anuncio', 'Anuncio'), ('general', 'General'), ('email_verificado', 'Email Verificado'), ('password_changed', 'Contraseña Cambiada'), ('password_reset', 'Contraseña Restablecida'), ('login_failed', 'Intento de Login Fallido'), ('account_security', 'Alerta de Seguridad'), ('alerta_rector', 'Alerta para Rector'), ('novedad_academica', 'Novedad Académica'), ('finanzas_educoins', 'Finanzas de EduCoins'), ('subasta_abierta', 'Subasta Abierta')], max_length=30),
        ),
    ]
