# Generated by Django 5.2.6 on 2026-06-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la institución')),
                ('codigo_dane', models.CharField(blank=True, help_text='Código único de identificación de la institución (DANE u otro)', max_length=50, null=True, unique=True, verbose_name='Código DANE')),
                ('activo', models.BooleanField(default=True, verbose_name='Institución activa')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
    ]
