# Generated by Django 5.2.6 on 2026-06-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='color_primario',
            field=models.CharField(default='#f97316', help_text='Color corporativo principal en formato hexadecimal (ej. #f97316)', max_length=7, verbose_name='Color primario'),
        ),
        migrations.AddField(
            model_name='institution',
            name='color_secundario',
            field=models.CharField(default='#3b82f6', help_text='Color corporativo secundario en formato hexadecimal (ej. #3b82f6)', max_length=7, verbose_name='Color secundario'),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='instituciones/logos/', verbose_name='Logo institucional'),
        ),
    ]
