# Generated by Django 5.2.6 on 2026-06-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institutions', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='institutions.institution', verbose_name='Institución educativa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador Global'), ('rector', 'Rector'), ('coordinador', 'Coordinador'), ('docente', 'Docente'), ('estudiante', 'Estudiante')], default='estudiante', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'rector')), fields=('institucion',), name='unique_rector_per_institution', violation_error_message='Esta institución ya tiene un rector asignado.'),
        ),
    ]
