services:
  db:
    image: mysql:8.0
    container_name: edubid_mysql
    restart: always
    environment:
      MYSQL_DATABASE: edubid_db
      MYSQL_USER: edubid_admin
      MYSQL_PASSWORD: ivnmtz09
      MYSQL_ROOT_PASSWORD: root_password_segura
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
