# Generated by Django 5.2.6 on 2026-06-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada')], default='active', max_length=10)),
                ('fecha_fin', models.DateTimeField()),
                ('valor_minimo', models.PositiveIntegerField(default=1, help_text='Valor mínimo para la primera puja en esta subasta')),
                ('incremento_minimo', models.PositiveIntegerField(default=10, help_text='Incremento mínimo requerido entre pujas consecutivas')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-cantidad'],
            },
        ),
    ]
