# Generated by Django 5.2.6 on 2026-06-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='incremento_minimo',
            field=models.PositiveIntegerField(default=10, help_text='Incremento mínimo requerido entre pujas consecutivas'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='valor_minimo',
            field=models.PositiveIntegerField(default=1, help_text='Valor mínimo para la primera puja en esta subasta'),
        ),
    ]
