# Generated by Django 5.2.6 on 2026-06-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-cantidad_educoins']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='cantidad',
            new_name='cantidad_educoins',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='incremento_minimo',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='valor_minimo',
        ),
        migrations.AddField(
            model_name='auction',
            name='incremento_minimo_educoins',
            field=models.PositiveIntegerField(default=10, help_text='Incremento mínimo en EduCoins requerido entre pujas consecutivas'),
        ),
        migrations.AddField(
            model_name='auction',
            name='valor_minimo_educoins',
            field=models.PositiveIntegerField(default=1, help_text='Valor mínimo en EduCoins para la primera puja en esta subasta'),
        ),
    ]
