# Generated by Django 5.2.6 on 2026-09-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAuctionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_docente', to='auctions.auction')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_puja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de puja por docente',
                'verbose_name_plural': 'Permisos de puja por docente',
                'unique_together': {('estudiante', 'auction')},
            },
        ),
    ]
