# Generated by Django 5.2.6 on 2026-06-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('earn', 'Ganado'), ('spend', 'Gastado'), ('reset', 'Reinicio')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='groups.group')),
            ],
            options={
                'ordering': ['-creado'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('bloqueado', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='groups.group')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='tokens.period')),
            ],
        ),
    ]
