# Generated by Django 5.2.6 on 2026-06-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cointransaction',
            old_name='cantidad',
            new_name='cantidad_educoins',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='bloqueado',
            new_name='bloqueado_educoins',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='saldo',
            new_name='saldo_educoins',
        ),
    ]
